### ISSUE TITLE
PrivateKit Server Design

### ISSUE THREAD

**Issue by philmui** [safe-paths-contrib/covid-safe-paths#6]
- [x] [Private Kit Service](https://docs.google.com/document/d/18laAJLw2usCZvEF7pPF3b_m6IUBr-Vjplz1f7byltTM/edit) Google Doc outlines the design
- [x] API Design: https://anypoint.mulesoft.com/exchange/07dc70f5-4764-4132-97cf-e71bfac3f7fd/privatekit-covid19/minor/2.0/
- [ ] Convert Mulesoft API interface into a textual document
- [ ] Authentication on the service
- [ ] Confirmation from Sam's Team
	- [ ] Design consensus
	- [ ] Database decision

**Comment by kujenga** [comment]
Comments from Sam, SQL-based server may be the preference from health providers.

@ppadmanabhan-sf states that kubernetes work will be done by another team?

**Comment by kujenga** [comment]
Update from Standup: Implementation has started, teams seem to be are okay with it. Adding persistence layer today, then working on tests.

Need help because more bandwidth is needed:
- Survey piece of this

Once the framework is out, replicating it per-survey will require more work.

@ppadmanabhan-sf to make individual tickets for people to assist with this work.

**Comment by kujenga** [comment]
Uri will connect with @ppadmanabhan-sf  on more development resources.

**Comment by kujenga** [comment]
Update
- API spec is in a good place now
- Working with Uri on engineering resources
- Possibly will have something ready in a week

**Comment by kujenga** [comment]
Update: API design seems to be clear, coding work starts today with new team members. Just small little things from @aputinski 's perspective. Source of images is one open question, @ppadmanabhan-sf will add that in.

Branching will be needed, conditions will be present. Default is "go to the next question", condition field is optional. Based around the index of the questions, which is documented. Changed from previous API designs. This should now be in the docs.

@troach-sf points out that API for Waypoints may not be needed for initial version. Will have a follow up conversation on this right after standup today.

**Comment by kujenga** [comment]
Update: iterated on survey design, it is complete. Not going to do waypoints or heatmap implementation anymore.

Concentrating just on surveys now.

**Comment by kujenga** [comment]
Update: hoping to have everything done for Monday!

**Comment by kujenga** [comment]
Overall update from @ppadmanabhan-sf:

Code looks great, hoping to have it deployed. There is a deployment currently, @imanzano has it deployed in his own Heroku account.

**Comment by kujenga** [comment]
Adapting this to handle multiple languages, then will close this out.

**Comment by kujenga** [comment]
Closing this the language functionality added.
